[dependencies]
base = "0.10.4"
vector = "0.2.0"
swb = "1.1.1"
streams = "https://github.com/research-ag/streams#dc19552e75fe7c630f47d3f9e2a3f676bf39e624"
memory-region = "0.1.1"

[toolchain]
moc = "0.10.4"
wasmtime = "17.0.2"
