name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

env:
  mops_version: latest

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make bin directory
        run: mkdir -p /home/runner/bin

      - name: "install mops"
        run: |          
          npm i -g ic-mops@${{ env.mops_version }}

      - name: "test"
        run: mops test
