name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

env:
  mops_version: 0.12.1
  moc_version: 0.10.2
  wasmtime_version: 14.0.4

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make bin directory
        run: mkdir -p /home/runner/bin

      - name: "install Motoko binaries"
        run: |
          wget https://github.com/dfinity/motoko/releases/download/${{ env.moc_version }}/motoko-Linux-x86_64-${{ env.moc_version }}.tar.gz
          tar -xzf motoko-Linux-x86_64-${{ env.moc_version }}.tar.gz -C /home/runner/bin
          echo "/home/runner/bin" >> $GITHUB_PATH

      - name: "Install wasmtime"
        run: |
          wget https://github.com/bytecodealliance/wasmtime/releases/download/v${{ env.wasmtime_version }}/wasmtime-v${{ env.wasmtime_version }}-x86_64-linux.tar.xz
          tar -xf wasmtime-v${{ env.wasmtime_version }}-x86_64-linux.tar.xz --transform='s/.*\///' -C /home/runner/bin

      - name: "install mops"
        run: |          
          npm i -g ic-mops@${{ env.mops_version }}

      - name: "test"
        run: make -C test
